apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: author
  name: author
spec:
  ports:
  - name: "4502"
    port: 4502
    targetPort: 4502
  selector:
    io.kompose.service: author
  type: NodePort
