apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: author
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: author
    spec:
      containers:
      - image: 192.168.0.152:5000/aem-author:latest
        imagePullPolicy: Always
        name: author
        ports:
        - containerPort: 4502
        resources: {}
      restartPolicy: Always
status: {}
