apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: publisher
  name: publisher
spec:
  ports:
  - name: "4503"
    port: 4503
    targetPort: 4503
  selector:
    io.kompose.service: publisher
  type: NodePort
