apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: publisher
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: publisher
    spec:
      containers:
      - image: 192.168.0.152:5000/aem-publisher:latest
        imagePullPolicy: Always
        name: publisher
        ports:
        - containerPort: 4503
        resources: {}
      restartPolicy: Always
status: {}
